/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppLeaveRouteImport } from './routes/_app/leave'
import { Route as AppOrganisationRouteImport } from './routes/_app/organisation'
import { Route as AppPayrollIndexRouteImport } from './routes/_app/payroll/index'
import { Route as AppPayrollPayslipIdRouteImport } from './routes/_app/payroll/$payslipId'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppPeopleEmployeeIdRouteImport } from './routes/_app/people/$employeeId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganisationRoute = AppOrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollPayslipIdRoute = AppPayrollPayslipIdRouteImport.update({
  id: '/payroll/$payslipId',
  path: '/payroll/$payslipId',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleEmployeeIdRoute = AppPeopleEmployeeIdRouteImport.update({
  id: '/people/$employeeId',
  path: '/people/$employeeId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/calendar': typeof AppCalendarRoute
  '/leave': typeof AppLeaveRoute
  '/organisation': typeof AppOrganisationRoute
  '/payroll/$payslipId': typeof AppPayrollPayslipIdRoute
  '/people/$employeeId': typeof AppPeopleEmployeeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/people/': typeof AppPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/attendance': typeof AppAttendanceRoute
  '/audit': typeof AppAuditRoute
  '/calendar': typeof AppCalendarRoute
  '/leave': typeof AppLeaveRoute
  '/organisation': typeof AppOrganisationRoute
  '/': typeof AppIndexRoute
  '/payroll/$payslipId': typeof AppPayrollPayslipIdRoute
  '/people/$employeeId': typeof AppPeopleEmployeeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/people': typeof AppPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/leave': typeof AppLeaveRoute
  '/_app/organisation': typeof AppOrganisationRoute
  '/_app/': typeof AppIndexRoute
  '/_app/payroll/$payslipId': typeof AppPayrollPayslipIdRoute
  '/_app/people/$employeeId': typeof AppPeopleEmployeeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/audit'
    | '/calendar'
    | '/leave'
    | '/organisation'
    | '/payroll/$payslipId'
    | '/people/$employeeId'
    | '/api/auth/$'
    | '/payroll/'
    | '/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/attendance'
    | '/audit'
    | '/calendar'
    | '/leave'
    | '/organisation'
    | '/'
    | '/payroll/$payslipId'
    | '/people/$employeeId'
    | '/api/auth/$'
    | '/payroll'
    | '/people'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/attendance'
    | '/_app/audit'
    | '/_app/calendar'
    | '/_app/leave'
    | '/_app/organisation'
    | '/_app/'
    | '/_app/payroll/$payslipId'
    | '/_app/people/$employeeId'
    | '/api/auth/$'
    | '/_app/payroll/'
    | '/_app/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organisation': {
      id: '/_app/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof AppOrganisationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/$payslipId': {
      id: '/_app/payroll/$payslipId'
      path: '/payroll/$payslipId'
      fullPath: '/payroll/$payslipId'
      preLoaderRoute: typeof AppPayrollPayslipIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$employeeId': {
      id: '/_app/people/$employeeId'
      path: '/people/$employeeId'
      fullPath: '/people/$employeeId'
      preLoaderRoute: typeof AppPeopleEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppOrganisationRoute: typeof AppOrganisationRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPayrollPayslipIdRoute: typeof AppPayrollPayslipIdRoute
  AppPeopleEmployeeIdRoute: typeof AppPeopleEmployeeIdRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppAuditRoute: AppAuditRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppOrganisationRoute: AppOrganisationRoute,
  AppIndexRoute: AppIndexRoute,
  AppPayrollPayslipIdRoute: AppPayrollPayslipIdRoute,
  AppPeopleEmployeeIdRoute: AppPeopleEmployeeIdRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
